// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF_lab1.Models;

public partial class Employee
{
    public int EmpID { get; set; }

    public string EmpName { get; set; }

    public int? DeptID { get; set; }

    public virtual Department Dept { get; set; }
}