// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Demo1.API.Models;

public partial class Course
{
    [Key]
    public int id { get; set; }

    [StringLength(50)]
    public string crs_name { get; set; }

    [StringLength(150)]
    public string crs_desc { get; set; }

    public int? Duration { get; set; }
}