// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Demo1.API.Models;

public partial class Lab1ApiContext : DbContext
{
    public Lab1ApiContext()
    {
    }

    public Lab1ApiContext(DbContextOptions<Lab1ApiContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Courses { get; set; }

  
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Course>(entity =>
        {
            entity.Property(e => e.id).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}